apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-auto-ingress
spec:
  selector:
    matchLabels:
      app: kubernetes-auto-ingress
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-auto-ingress
    spec:
      containers:
      - name: kubernetes-auto-ingress
        image: maayanlab/kubernetes-auto-ingress:v0.1.0
        env:
        - name: "AUTO_INGRESS_SECRET"
          value: "secret"
        - name: "AUTO_INGRESS_SERVER_NAME"
          value: "amp.pharm.mssm.edu"
        imagePullPolicy: Always
