apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernete-auto-ingress
spec:
  selector:
    matchLabels:
      app: kubernetes-auto-ingress
  replicas: 1
  template:
    metadata:
      labels:
        app: kubernetes-auto-ingress
    spec:
      containers:
      - name: kubernetes-auto-ingress
        image: hxquangnhat/kubernetes-auto-ingress
        env:
        - name: "AUTO_INGRESS_SECRET"
          value: "secret"
        - name: "AUTO_INGRESS_SERVER_NAME"
          value: "maayanlab.net"
        imagePullPolicy: Always
